# Header
menu:
  Home: /
  Author: /author
  Desktop: /desktop
  Health: /health
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
- tagcloud
- archive
  #- tag

# Miscellaneous
google_analytics: UA-57044545-1
favicon: /images/favicon.png
twitter: 513256254
google_plus: 110511550415133053098
fb_admins:
fb_app_id:
